services:
  app:
    container_name: app
    build:
      context: app/.
    command: python manage.py runserver ${HOST}:${PORT}
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.4-alpine
    ports:
      - ${SQL_PORT}:${SQL_PORT}
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_PORT=${SQL_PORT}