services:
  app:
    build:
      context: app/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
     - DJANGO_SETTINGS_MODULE=base.settings
    depends_on:
      - db
  db:
    image: postgres:14.4-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=motorenger
      - POSTGRES_PASSWORD=motorenger
      - POSTGRES_DB=motorenger
      - POSTGRES_PORT=5432