# Generated by Django 4.2 on 2023-05-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0004_cartproductm2m_price_cartproductm2m_price_currency"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cart",
            field=models.OneToOneField(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
            ),
        ),
    ]
