# Generated by Django 4.2 on 2023-05-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_alter_cart_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartproductm2m",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cartproductm2m",
            name="price_currency",
        ),
    ]
