# Generated by Django 4.2 on 2023-04-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_type_clothessize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('clothes', 'Clothes'), ('footwear', 'Footwear')], editable=False, max_length=8),
        ),
    ]
