# Generated by Django 4.2 on 2023-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[("clothes", "Clothes"), ("footwear", "Footwear")], max_length=8
            ),
        ),
    ]
