name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ vars.DEBUG }}
      SECRET_KEY: ${{ vars.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ vars.ALLOWED_HOSTS }}
      SQL_ENGINE: ${{ vars.SQL_ENGINE }}
      SQL_DATABASE: ${{ vars.SQL_DATABASE }}
      SQL_USER: ${{ vars.SQL_USER }}
      SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
      SQL_HOST: ${{ vars.SQL_HOST }}
      SQL_PORT: ${{ vars.SQL_PORT }}
      DATABASE: ${{ vars.DATABASE }}
      INTERNAL_IPS: ${{ vars.INTERNAL_IPS }}
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}


    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ vars.SQL_DATABASE }}      
          POSTGRES_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          POSTGRES_USER: ${{ vars.SQL_USER }}
        ports:
          - ${{ vars.SQL_PORT }}:${{ vars.SQL_PORT }}
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./app/
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../app/requirements.txt
    - name: Run Tests
      run: |
        pytest
